# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='helloworld',
  syntax='proto3',
  serialized_options=_b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\x10helloworld.proto\x12\nhelloworld\";\n\x0b\x44\x61taRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07mensaje\x18\x02 \x01(\t\x12\x0f\n\x07\x64\x65stino\x18\x03 \x01(\t\"\x1c\n\tDataReply\x12\x0f\n\x07mensaje\x18\x01 \x01(\t2\xcd\x01\n\nMensajeria\x12?\n\x0bSendMensaje\x12\x17.helloworld.DataRequest\x1a\x15.helloworld.DataReply\"\x00\x12\x45\n\x11SubscribeMessages\x12\x15.helloworld.DataReply\x1a\x15.helloworld.DataReply\"\x00\x30\x01\x12\x37\n\x05Salir\x12\x15.helloworld.DataReply\x1a\x15.helloworld.DataReply\"\x00\x32L\n\nAllClients\x12>\n\ngetClients\x12\x15.helloworld.DataReply\x1a\x15.helloworld.DataReply\"\x00\x30\x01\x32N\n\x0b\x41llMessages\x12?\n\x0bgetMessages\x12\x15.helloworld.DataReply\x1a\x15.helloworld.DataReply\"\x00\x30\x01\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_DATAREQUEST = _descriptor.Descriptor(
  name='DataRequest',
  full_name='helloworld.DataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='helloworld.DataRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='helloworld.DataRequest.mensaje', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destino', full_name='helloworld.DataRequest.destino', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=91,
)


_DATAREPLY = _descriptor.Descriptor(
  name='DataReply',
  full_name='helloworld.DataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensaje', full_name='helloworld.DataReply.mensaje', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['DataRequest'] = _DATAREQUEST
DESCRIPTOR.message_types_by_name['DataReply'] = _DATAREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataRequest = _reflection.GeneratedProtocolMessageType('DataRequest', (_message.Message,), {
  'DESCRIPTOR' : _DATAREQUEST,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.DataRequest)
  })
_sym_db.RegisterMessage(DataRequest)

DataReply = _reflection.GeneratedProtocolMessageType('DataReply', (_message.Message,), {
  'DESCRIPTOR' : _DATAREPLY,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:helloworld.DataReply)
  })
_sym_db.RegisterMessage(DataReply)


DESCRIPTOR._options = None

_MENSAJERIA = _descriptor.ServiceDescriptor(
  name='Mensajeria',
  full_name='helloworld.Mensajeria',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=124,
  serialized_end=329,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMensaje',
    full_name='helloworld.Mensajeria.SendMensaje',
    index=0,
    containing_service=None,
    input_type=_DATAREQUEST,
    output_type=_DATAREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SubscribeMessages',
    full_name='helloworld.Mensajeria.SubscribeMessages',
    index=1,
    containing_service=None,
    input_type=_DATAREPLY,
    output_type=_DATAREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Salir',
    full_name='helloworld.Mensajeria.Salir',
    index=2,
    containing_service=None,
    input_type=_DATAREPLY,
    output_type=_DATAREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MENSAJERIA)

DESCRIPTOR.services_by_name['Mensajeria'] = _MENSAJERIA


_ALLCLIENTS = _descriptor.ServiceDescriptor(
  name='AllClients',
  full_name='helloworld.AllClients',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=331,
  serialized_end=407,
  methods=[
  _descriptor.MethodDescriptor(
    name='getClients',
    full_name='helloworld.AllClients.getClients',
    index=0,
    containing_service=None,
    input_type=_DATAREPLY,
    output_type=_DATAREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALLCLIENTS)

DESCRIPTOR.services_by_name['AllClients'] = _ALLCLIENTS


_ALLMESSAGES = _descriptor.ServiceDescriptor(
  name='AllMessages',
  full_name='helloworld.AllMessages',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=409,
  serialized_end=487,
  methods=[
  _descriptor.MethodDescriptor(
    name='getMessages',
    full_name='helloworld.AllMessages.getMessages',
    index=0,
    containing_service=None,
    input_type=_DATAREPLY,
    output_type=_DATAREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALLMESSAGES)

DESCRIPTOR.services_by_name['AllMessages'] = _ALLMESSAGES

# @@protoc_insertion_point(module_scope)
